made the change

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -53,5 +53,5 @@ jobs:
       - name: Test App
         run: npm test
 
-      - name: Test failure 
-        run: exit 1
+      # - name: Test failure 
+      #   run: exit 1
